add version support
Summary:
`--version` is being used in build_binaries.yml. adding support for it.

failure in github:
```
Run pip install dist/"${PACKAGE_FILE_NAME}"-*.whl --force-reinstall
  pip install dist/"${PACKAGE_FILE_NAME}"-*.whl --force-reinstall
  "${BINARY_NAME}" --version
  "${BINARY_NAME}" --help
  python -m lifeguard_lazy_imports --version
  shell: /bin/bash -e {0}
  env:
    PACKAGE_FILE_NAME: lifeguard_lazy_imports
    BINARY_NAME: lifeguard
    PYTHON_VERSION: 3.12
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.12.10/arm64
    PKG_CONFIG_PATH: /Users/runner/hostedtoolcache/Python/3.12.10/arm64/lib/pkgconfig
    Python_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.12.10/arm64
    Python2_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.12.10/arm64
    Python3_ROOT_DIR: /Users/runner/hostedtoolcache/Python/3.12.10/arm64
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
Processing ./dist/lifeguard_lazy_imports-0.0.0-py3-none-macosx_11_0_arm64.whl
Installing collected packages: lifeguard-lazy-imports
Successfully installed lifeguard-lazy-imports-0.0.0
error: unexpected argument '--version' found

  tip: to pass '--version' as a value, use '-- --version'

Usage: lifeguard [OPTIONS] [DB_PATH] [OUTPUT_PATH]
       lifeguard <COMMAND>

For more information, try '--help'.
```

Reviewed By: brittanyrey

Differential Revision: D98961998

fbshipit-source-id: a9e356dafba87f361a70b6020fc50971440df1d1